### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by SteveTanggithub** [RicherMans/CED#1]
**my torch version is 1.13.0+cu116, torch-audiomentations verson is 0.11.0, cuda version is 11.6. The error shows below when I try to train the model after i have prepared the data. Can u know how to solve this?**

(base) root@gpu20-a40:/home/imoualgorithm_dev/376285/code/CED-main# python3 run.py train trainconfig/full_audiotransformer_mini_T_Ensemble5014_chunk10.yaml
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    import dataset
  File "/home/imoualgorithm_dev/376285/code/CED-main/dataset.py", line 10, in <module>
    import utils
  File "/home/imoualgorithm_dev/376285/code/CED-main/utils.py", line 13, in <module>
    **import torch_audiomentations as wavtransforms**
  File "/opt/conda/lib/python3.8/site-packages/torch_audiomentations/__init__.py", line 1, in <module>
    from .augmentations.background_noise import AddBackgroundNoise
  File "/opt/conda/lib/python3.8/site-packages/torch_audiomentations/augmentations/background_noise.py", line 11, in <module>
    from ..utils.io import Audio
  File "/opt/conda/lib/python3.8/site-packages/torch_audiomentations/utils/io.py", line 5, in <module>
    import librosa
  File "/opt/conda/lib/python3.8/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/opt/conda/lib/python3.8/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/opt/conda/lib/python3.8/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/opt/conda/lib/python3.8/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/opt/conda/lib/python3.8/site-packages/librosa/util/__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/opt/conda/lib/python3.8/site-packages/librosa/util/utils.py", line 10, in <module>
    import numba
  File "/opt/conda/lib/python3.8/site-packages/numba/__init__.py", line 212, in <module>
    import numba.typed
  File "/opt/conda/lib/python3.8/site-packages/numba/typed/__init__.py", line 1, in <module>
    from .typeddict import Dict
  File "/opt/conda/lib/python3.8/site-packages/numba/typed/typeddict.py", line 23, in <module>
    def _make_dict(keyty, valty):
  File "/opt/conda/lib/python3.8/site-packages/numba/core/decorators.py", line 260, in njit
    return jit(*args, **kws)
  File "/opt/conda/lib/python3.8/site-packages/numba/core/decorators.py", line 183, in jit
    return wrapper(pyfunc)
  File "/opt/conda/lib/python3.8/site-packages/numba/core/decorators.py", line 210, in wrapper
    disp = dispatcher(py_func=func, locals=locals,
  File "/opt/conda/lib/python3.8/site-packages/numba/core/dispatcher.py", line 746, in __init__
    self.targetctx = self.targetdescr.target_context
  File "/opt/conda/lib/python3.8/site-packages/numba/core/registry.py", line 47, in target_context
    return self._toplevel_target_context
  File "/opt/conda/lib/python3.8/site-packages/numba/core/utils.py", line 277, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/conda/lib/python3.8/site-packages/numba/core/registry.py", line 31, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "/opt/conda/lib/python3.8/site-packages/numba/core/base.py", line 259, in __init__
    self.init()
  File "/opt/conda/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/numba/core/cpu.py", line 47, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "/opt/conda/lib/python3.8/site-packages/numba/core/codegen.py", line 1086, in __init__
    self._init(self._llvm_module)
  File "/opt/conda/lib/python3.8/site-packages/numba/core/codegen.py", line 1091, in _init
    target = ll.Target.from_triple(ll.get_process_triple())
  File "/opt/conda/lib/python3.8/site-packages/llvmlite/binding/targets.py", line 197, in from_triple
    raise RuntimeError(str(outerr))
**RuntimeError: Unable to find target for this triple (no targets are registered)**
Segmentation fault (core dumped)

**Comment by RicherMans** [comment]
Hey,
I think its related to `torch_audiomentations` and its dependence with `numba`.
I checked my `numba` version and I run `0.56.4`.
Maybe try to `pip3 install numba==0.56.4`?

Btw for librosa I run `0.8.1`

**Comment by SteveTanggithub** [comment]
**i download the full audioset data from other way and my full.tsv is like below:**
filename hdf5path
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-BHv6l9GZKc.wav data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-n5l0wbm7os.wav data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-1PdYSCS1Ao.wav data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-1caqJsJZss.wav data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-jsDbiCYqGA.wav data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-FrWrGD3sG4.wav data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-2uNe2Uub30.wav data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-Dy-DKiJw_M.wav data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-KC-hGQTIOg.wav data/full_train/hdf5/full_0.h5
**i use the logitspath u provide, but got the error:**
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/imoualgorithm_dev/376285/code/CED-main/dataset.py", line 169, in __getitem__
    hdf5path_data = self.fname_to_hdf5[fname]
**KeyError: 'uCUPXiawrJc_20.000.wav'
it seems like i don't have these wav files in my data? my data must be completely same with yours? Or did i do something wrong? i am a little confused.**

**Comment by RicherMans** [comment]
Hey there Steve,
so I'm super sorry about that stupid stuff there but the main reason for this error is my own dataset.
So for some reason I downloaded the balanced and unbalanced datasets using different scripts, which lead to a naming discrepancy.
The balanced files in my data are: `YOUTUBEID_STARTTIME.wav`
The unbalanced are: `YOUTUBEID_STARTTIME_ENDTIME.wav`

I actually mentioned that in the README.

How to fix that?
Well, please go into the `logits/ensemble5014/full/chunk_10` folder and then use some simple script to convert all the "wrong" filenames:

```python
import pandas as pd
from pathlib import Path
YOUR_MAPPING_DICT = {"uCUPXiawrJc_20.000_30.000.wav": "uCUPXiawrJc_20.000.wav"}
for p in Path('.').glob('*.parquet'):
     df = pd.read_parquet(p)
     df['filename'] = df['filename'].map(YOUR_MAPPING_DICT)
     df.to_parquet(p)
```

But actually, I would recommend you to maybe try to just for your balanced subset to change the filenames to `YOUTUBEID_STARTTIME.wav` just crop the `ENDTIME` if you know what I mean.

Did that help?

Heinrich

**Comment by SteveTanggithub** [comment]
emm, the balanced data is not a big deal but the unbalanced one. The filenames of my unbalanced data is all like **YOUTUBEID.wav** and i don't have the start time and end time infor. How can i adjust my data or make script to make them suit ur setting? :(((

**Comment by RicherMans** [comment]
Hey Steve,
thats fortunately pretty simple I guess.
The following should work:

First: `cd logits/ensemble5014/full/chunk_10`

Then:

```python
import pandas as pd
from pathlib import Path

for p in Path('.').glob("*parquet"):
     df = pd.read_parquet(p)
     df['filename'] = df['filename'].str[:11]+'.wav'
     df.to_parquet(p,index=False, compression='brotli')
```

**Comment by SteveTanggithub** [comment]
i got a new issue, some wavs in logits didn't exist in my data, so it also comes out the error before. Do i need add some judgement condition in somewhere of code? Or is there some solutions?

**Comment by RicherMans** [comment]
Hey Steve,
Sorry for that too, I think I got a script for that:


```python
  import pandas as pd                                                                                                                                                                           
  import h5py
  from pathlib import Path
   
  data_df = pd.read_csv('YOUR_INPUT_CSV',sep='\t')
  data_df['fn'] = data_df['filename'].str.split('/').str[-1]
   
  for p in Path('logits/ensemble5014/full/chunk_10/').glob('*ep*parquet'):
      print(f"Patching {p}")
      h5path = str(p).replace('.parquet','.h5')
      df = pd.read_parquet(p)
      df['filename'] = df['filename'].str[:11]+'.wav'
      idxs = df.index[df['filename'].isin(data_df['fn'])].to_list()
      f = h5py.File(h5path,'r+')
   
      for key in f.keys():
          logits_key = f[key]
          logits_shape_left = logits_key.shape[1:]
          logits_key[:len(idxs)] = logits_key[idxs]
          logits_key.resize((len(idxs),*logits_shape_left))
      # Also strip the parquet
      df = df.iloc[idxs].reset_index(drop=True)
      df.to_parquet(p,index=False, compression='brotli')

```

Just change the `YOUR_INPUT_CSV` with your `.tsv/csv` data and I hope it works. I tested it right now locally and seems to be working.
Kind regards,
Heinrich

**Comment by RicherMans** [comment]
Hey @SteveTanggithub did it work out or is there still a problem?

**Comment by SteveTanggithub** [comment]
hi, thanks for ur attention. I am still running the script now, it's so slow. Is it normal bacause I have run it over 5 hours?

**Comment by RicherMans** [comment]
Hey,
seems like something is wrong? On my machine it took about 30 secs maybe.

**Comment by SteveTanggithub** [comment]
My data is like the below, the file names all start with a _Y_  and all have 12 symbols. So I change the filename in logits by using:
`df['filename'] = "Y" + df['filename'].str[:11]+'.wav'`

But the code runs extremely slowly :(

filename	hdf5path
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-BHv6l9GZKc.wav	data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-n5l0wbm7os.wav	data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-1PdYSCS1Ao.wav	data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-1caqJsJZss.wav	data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-jsDbiCYqGA.wav	data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-FrWrGD3sG4.wav	data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-2uNe2Uub30.wav	data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-Dy-DKiJw_M.wav	data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-KC-hGQTIOg.wav	data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-iY50CmUhLs.wav	data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-DIgLZVQZQs.wav	data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-NU9h17epFE.wav	data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-9tIbTh-K-E.wav	data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-jrXM3-Ow2g.wav	data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-1atj274fRw.wav	data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-QbqK48qpmg.wav	data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-iKcpbSSIEc.wav	data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-8_eB4JB6IA.wav	data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-hrVe9WBtx8.wav	data/full_train/hdf5/full_0.h5
/home/imoualgorithm_dev/376285/Database/audioset/full_total_wavs/Y-mm48nmnL4E.wav	data/full_train/hdf5/full_0.h5

**Comment by RicherMans** [comment]
Hey so can you trace it where exactly it runs slow? Is  `df['filename'] = "Y" + df['filename'].str[:11]+'.wav'` slow?

**Comment by SteveTanggithub** [comment]
I have processed the data, and it's training now. It takes nearly 1 hour for every epoch with GPU NVIDIA A40, is it normal? BTW, the model won't be validated until the total training process is done?

**Comment by RicherMans** [comment]
Usually validation is done every ~3-5 epochs, because validation takes some time.
Also the speed seems to be okay, I didn't have an A40, but the longest I trained was for 4 days for the -Base model.
Note that if you just change the batchsize , performance will decrease slightly but training speed might improve a lot.

The smaller models (-Tiny, -Mini) usually took about 1-2 days on batchsize 128 and less than 1 day on batchsize 32.

**Comment by SteveTanggithub** [comment]
I tested the training code with 6 epochs using balanced data, and it shows the information below after the end of training which saves the average model pt file : 
**munmap_chunk(): invalid pointer**
Did I need any other files? Have you ever met the situation before?

**Comment by RicherMans** [comment]
Hey there,
I have never met this situation before. Is the checkpoint's size correct like does it have some data? Can you try and open the checkpoint with `torch.load()` ?

**Comment by RicherMans** [comment]
Hey @SteveTanggithub ,
Did it work so far or is there still an issue?

**Comment by SteveTanggithub** [comment]
sry for the late reply, the previous problem has not been solved, I feel that there may be something wrong with my data. I give up for reproducing ur work for now. And there is not very clear for reproducing the results by myself, such as establishing the code for data augmentation seeds. But thanks for ur help. :)

**Comment by RicherMans** [comment]
Hey sorry that it didn't work out. To be honest I actually just have this repo that people use the model as-is and maybe expand upon the codebase, instead of training from scratch.
I do my best to optimize the code in the future, but I believe that the main problem is not the code, but the "differences" in people having obtained Audioset through different means and thus having a non-standard dataset.

Sorry that it didn't work, but should we close the issue then?

**Comment by SteveTanggithub** [comment]
sure, u are free to close the issue



---Original---
From: "Heinrich ***@***.***&gt;
Date: Thu, Sep 21, 2023 14:41 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [RicherMans/CED] Training error (Issue #1)




 
Hey sorry that it didn't work out. To be honest I actually just have this repo that people use the model as-is and maybe expand upon the codebase, instead of training from scratch.
 I do my best to optimize the code in the future, but I believe that the main problem is not the code, but the "differences" in people having obtained Audioset through different means and thus having a non-standard dataset.
 
Sorry that it didn't work, but should we close the issue then?
