### ISSUE TITLE
FYI: Android APKs for CED

### ISSUE THREAD

**Issue by csukuangfj** [RicherMans/CED#13]
Please see
https://k2-fsa.github.io/sherpa/onnx/audio-tagging/apk.html

![Screenshot 2024-04-19 at 15 28 38](https://github.com/RicherMans/CED/assets/5284924/2015cddc-5d1c-4642-81d2-b7f8eca1e4df)

**Comment by RicherMans** [comment]
非常感谢你的支持，方军！
