### ISSUE TITLE
any way to train with 8k audio ?

### ISSUE THREAD

**Issue by herbiel** [RicherMans/CED#16]

**Comment by RicherMans** [comment]
Hey,
If you just like to use the models, just upsample the audio to 16k.
Otherwise just train with 8k audio. There is no difference.

**Comment by herbiel** [comment]
python3 run.py train trainconfig/balanced_mixup_base_T_ensemble5014_chunk10.yaml --logitspath logits/audiotransformer_base_4740/my_data/chunk_10 --train_data my_data.tsv 

i try train from my data,but show this error
Traceback (most recent call last):
  File "/opt/CED/venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'hdf5path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/CED/run.py", line 575, in <module>
    Fire(Runner)
  File "/opt/CED/venv/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/CED/venv/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/CED/venv/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/opt/CED/run.py", line 366, in train
    train_dataset = dataset.LogitsReader(
  File "/opt/CED/dataset.py", line 27, in __init__
    self.fname_to_hdf5 = data_frame.set_index(
  File "/opt/CED/venv/lib/python3.10/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/opt/CED/venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'hdf5path'

**Comment by RicherMans** [comment]
Hey, 
as the error suggest your data is missing the 'hdf5path' column.

As the Readme states [in the data preparation part](https://github.com/RicherMans/CED?tab=readme-ov-file#1-preparing-data), you need to:

1. Prepare the csv/tsv:
```
find data/balanced/ -type f | awk 'BEGIN{print "filename"}{print}' > data/balanced.tsv
```
2. Dump the data into a h5:

```
python3 scripts/wavlist_to_hdf5.py data/balanced.tsv data/balanced_train/
```

This will generate `data/balanced_train/labels/balanced.tsv`, which can be used for training.


As the README states, the result should look like this:

```
filename	labels	hdf5path
data/eval/--4gqARaEJE.wav	73;361;74;72	data/eval_data/hdf5/eval_0.h5
data/eval/--BfvyPmVMo.wav	419	data/eval_data/hdf5/eval_0.h5
data/eval/--U7joUcTCo.wav	47	data/eval_data/hdf5/eval_0.h5
data/eval/-0BIyqJj9ZU.wav	21;20;17	data/eval_data/hdf5/eval_0.h5
```

**  Important Note **

Your filenames need to be identical to mine. If they are not, the logits cannot be found.
If your names are different, refer to https://github.com/RicherMans/CED/issues/1#issuecomment-1705810589.

**Comment by herbiel** [comment]
![image](https://github.com/RicherMans/CED/assets/31093300/4f98fbab-d036-42c7-b023-91370cc338f1)
map is so low ?

**Comment by RicherMans** [comment]
Hey there,
seems that you haven't adjusted the spectrograms.

pass:
```python
(
win_size=256
hop_size=80
n_fft=256,
)
```

to the model.

Also I think I hardcoded the sampling rate for the mel spectrograms https://github.com/RicherMans/CED/blob/d13974b9144a7314729dc55a69175c8330ce9614/models/audiotransformer.py#L203.
That needs also to be changed accordingly.

**Comment by herbiel** [comment]
![image](https://github.com/RicherMans/CED/assets/31093300/13a1e414-d155-45de-93c8-498abc68493e)
i have changed like them
![image](https://github.com/RicherMans/CED/assets/31093300/6e776cb6-5a10-43a3-9d7d-a7535cebb129)

**Comment by herbiel** [comment]
my_data_hdf5/labels/my_data.tsv likes
![image](https://github.com/RicherMans/CED/assets/31093300/a86c072f-bdd9-44c1-abcf-2f6acfcff4e5)
it loss the lables ?

**Comment by herbiel** [comment]
(
win_size=256
hop_size=80
n_fft=256,
) change like them ,the result still very bad

**Comment by RicherMans** [comment]
> my_data_hdf5/labels/my_data.tsv likes ![image](https://private-user-images.githubusercontent.com/31093300/332394634-a86c072f-bdd9-44c1-abcf-2f6acfcff4e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyOTM4NjcsIm5iZiI6MTcxNjI5MzU2NywicGF0aCI6Ii8zMTA5MzMwMC8zMzIzOTQ2MzQtYTg2YzA3MmYtYmRkOS00NGMxLWFiY2YtMmY2YWNmY2ZmNGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDEyMTI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2OWQ3MTNmMTcyMmE0MDA1ZjgxNmFjZDQ0ZmExNTEyMmJiYjkyNjI5MWNiOGE5MWM3MzJkNzFmYjA2NjIyOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rERi8YYoDPjyl3CxwNXwRW-MJoNdQlQwnI1hEapQUN8) it loss the lables ?

Sorry I don't get your point here.
It seems your data is not Audioset, so what do you expect to train right now?
The project focuses on pretraining on Audioset.
If you want to do classification on other datasets you can simply use the provided pretrained models and finetune.

**Comment by RicherMans** [comment]
@herbiel Is this issue resolved?

**Comment by herbiel** [comment]
![image](https://github.com/RicherMans/CED/assets/31093300/960255e8-d3d4-4a0c-a04e-6eda3638c252)

This is my folder structure
i follow you step with train from my own data,
find /opt/examples/audio/answerdetection/train/ -type f | awk 'BEGIN{print "filename"}{print}' > my_data.tsv

cat my_data.tsv 
filename
/opt/examples/audio/answerdetection/train/my_data.tsv
/opt/examples/audio/answerdetection/train/human/human.000.wav
/opt/examples/audio/answerdetection/train/human/human.001.wav
/opt/examples/audio/answerdetection/train/human/human.002.wav
/opt/examples/audio/answerdetection/train/human/human.004.wav
/opt/examples/audio/answerdetection/train/human/human.003.wav
/opt/examples/audio/answerdetection/train/ivr/ivr.000.wav
/opt/examples/audio/answerdetection/train/ivr/ivr.003.wav
/opt/examples/audio/answerdetection/train/ivr/ivr.004.wav
/opt/examples/audio/answerdetection/train/ivr/ivr.002.wav
/opt/examples/audio/answerdetection/train/ivr/ivr.001.wav
/opt/examples/audio/answerdetection/train/ringtone/ringtone.004.wav
/opt/examples/audio/answerdetection/train/ringtone/ringtone.003.wav
/opt/examples/audio/answerdetection/train/ringtone/ringtone.000.wav
/opt/examples/audio/answerdetection/train/ringtone/ringtone.002.wav
/opt/examples/audio/answerdetection/train/ringtone/ringtone.001.wav

after output h5 file , i will get this 
cat my_data_hdf5/labels/my_data.tsv 
filename	hdf5path
/opt/examples/audio/answerdetection/train/human/human.000.wav	my_data_hdf5/hdf5/my_data_0.h5
/opt/examples/audio/answerdetection/train/human/human.001.wav	my_data_hdf5/hdf5/my_data_0.h5
/opt/examples/audio/answerdetection/train/human/human.002.wav	my_data_hdf5/hdf5/my_data_0.h5
/opt/examples/audio/answerdetection/train/human/human.004.wav	my_data_hdf5/hdf5/my_data_0.h5
/opt/examples/audio/answerdetection/train/human/human.003.wav	my_data_hdf5/hdf5/my_data_0.h5
/opt/examples/audio/answerdetection/train/ivr/ivr.000.wav	my_data_hdf5/hdf5/my_data_0.h5
/opt/examples/audio/answerdetection/train/ivr/ivr.003.wav	my_data_hdf5/hdf5/my_data_0.h5
/opt/examples/audio/answerdetection/train/ivr/ivr.004.wav	my_data_hdf5/hdf5/my_data_0.h5
/opt/examples/audio/answerdetection/train/ivr/ivr.002.wav	my_data_hdf5/hdf5/my_data_0.h5
/opt/examples/audio/answerdetection/train/ivr/ivr.001.wav	my_data_hdf5/hdf5/my_data_0.h5
/opt/examples/audio/answerdetection/train/ringtone/ringtone.004.wav	my_data_hdf5/hdf5/my_data_0.h5
/opt/examples/audio/answerdetection/train/ringtone/ringtone.003.wav	my_data_hdf5/hdf5/my_data_0.h5
/opt/examples/audio/answerdetection/train/ringtone/ringtone.000.wav	my_data_hdf5/hdf5/my_data_0.h5
/opt/examples/audio/answerdetection/train/ringtone/ringtone.002.wav	my_data_hdf5/hdf5/my_data_0.h5
/opt/examples/audio/answerdetection/train/ringtone/ringtone.001.wav	my_data_hdf5/hdf5/my_data_0.h5

but without any labels in it ,can i train with this command
python3 run.py train trainconfig/balanced_mixup_base_T_ensemble5014_chunk10.yaml --logitspath YOUR_LOGITS_PATH --train_data my_data_hdf5/labels/my_data.tsv ?  this own audioset can't support ?

**Comment by RicherMans** [comment]
Hey,
so I am still super confused what are you trying to do there?
Train with different data on audioset labels? What do you expect that should happen?  And what has that to do with 8k audio at all? Did you try to use 16k audio by simply upsampling?

Do you know that Audioset is a name of a dataset, which is available [here](https://research.google.com/audioset/)?

Kind regards,
Heinrich

**Comment by herbiel** [comment]
so i can't use my own dataset ?

**Comment by RicherMans** [comment]
Hey there,
So I still have no idea what exactly you are trying to do.
The thread started without explanation about "any way to train with 8k audio ? ", which I responded with "yes, you can". Then you tried to train a classifier with your own data, without meaningful labels, which fails.
Again: Yes you can train on your own data.

I asked in this thread already twice and I ask it again:
**What exactly are you even trying to do?** 

We can only provide help if we understand the problem.
Kind regards,
Heinrich

**Comment by herbiel** [comment]
Some of my audio data has been classified, label is ringtone,human,and ivr,i want to use your project to train .

**Comment by RicherMans** [comment]
In that case, it should be easy:
1. Resample your data to 16k.
2. Follow [this notebook](https://github.com/jimbozhang/hf_transformers_custom_model_ced/blob/main/example_finetune_esc50.ipynb).
3. Sucess.

**Comment by herbiel** [comment]
Okay,thanks ,i will try

**Comment by herbiel** [comment]
in  this notebook ,where load the labes ?
![image](https://github.com/RicherMans/CED/assets/31093300/78429b8e-8a3e-459b-9807-1ee1aab01d90)
![image](https://github.com/RicherMans/CED/assets/31093300/9377415d-cdb3-496c-ad2e-9f0e94411a46)

after finetune_esc50,i test the model,but it show bird,and from his notebook,i don't see where it load the labels like bird

**Comment by RicherMans** [comment]
I'm closing this issue, this seems to be resolved.
Further note:
It is not very polite to open an issue with no context provided and only a single line of text.
Further, after solving the issue one should close it.
Lastly, I have still zero idea what you are trying to achieve, it seems you just randomly run code without second thought of what your goal is or what the training code will provide.
Please read an introduction to supervised learning or such and explain yourself better next time.
Kind regards,
Heinrich
