### ISSUE TITLE
可以用我们自己的数据来训练吗? 类型大概只有3-5种 可以支持实时识别吗？

### ISSUE THREAD

**Issue by herbiel** [RicherMans/CED#19]
可以用我们自己的数据来训练吗? 类型大概只有3-5种 可以支持实时识别吗？

**Comment by RicherMans** [comment]
实时识别这个看你怎么了解。你可以训练用1s/2s 这种颗粒的模型。目前ced模型都只是支持“离线”测试。
如果要低延迟的识别，也可以考虑[Streaming audiotransformers](https://github.com/RicherMans/SAT)

**Comment by herbiel** [comment]
那我想用自己的数据来训练 不用audioset 可以怎么操作？

**Comment by RicherMans** [comment]
当然，虽然建议拿预训练的模型。
