### ISSUE TITLE
Audio Embeddings from model

### ISSUE THREAD

**Issue by cvillela** [RicherMans/CED#3]
Hello! 
Congratulations on the model and results, they are truly impressive.
I was wondering if there is a way to get the latent audio representations without the final classification head using this repo.
Thanks for the attention to this matter,

Caio

**Comment by RicherMans** [comment]
Hey @cvillela,
currently I didn't implement that directly, but you can do the following:

```python
import models
import argparse

parser = argparse.ArgumentParser()
parser.add_argument(
    '-m',
    '--model',
    type=str,
    metavar=
    f"Public Checkpoint [{','.join(models.list_models())}] or Experiment Path",
    nargs='?',
    choices=models.list_models(),
    default='ced_mini')
args = parser.parse_args()

model = getattr(models, args.model)(pretrained=True)
model = model.to(DEVICE).eval()
def postprocessing(x):
     return x

model.forward_head = postprocessing

```

The default `forward head` method for the model is:
```python
        elif self.pooling == 'mean':
            x = x.mean(1)
            return self.outputlayer(x).sigmoid()
``` 
which you can also checkout [here](https://github.com/RicherMans/CED/blob/6a6b4ff86f3e0a105d69827df58784df3f1cbb63/models/audiotransformer.py#L303)

Note that all models use 4 patches in frequency, thus if you need to have some "patch-frame level" features, you need to first pool that sequence by 4.

**Comment by RicherMans** [comment]
Hey there @cvillela , did it solve the problem?

**Comment by cvillela** [comment]
Hello @RicherMans , I have not implemented it, but it does solve the problem! Thank you for your attention to this matter and fast response, I will close the issue.

Out of curiosity, what are the smallest/largest time frame that the model can extract embeddings from?
Thanks!
