### ISSUE TITLE
为什么这两种算出来的fbank特征差异那么大

### ISSUE THREAD

**Issue by yuyun2000** [RicherMans/CED#9]
我目前在端侧实现了第二种的计算，你有什么好的建议让我快速实现第一种特征？
原生（第一种）：
```
trans1=aut.MelSpectrogram(f_min=0,
                                sample_rate=16000,
                                win_length=512,
                                center=True,
                                n_fft=512,
                                f_max=8000,
                                hop_length=160,
                                n_mels=64)
trans2 = aut.AmplitudeToDB(top_db=120)
```

第二种（我的)：
```
mat = kaldi.fbank(wav,
                  num_mel_bins=64,
                  frame_length=32,
                  frame_shift=10,
                  dither=0.0,
                  energy_floor=0.0,
                  sample_frequency=16000,
                  window_type='hamming'
                  )
```

**Comment by RicherMans** [comment]
你好，
你可以参看 [torchaudio](https://pytorch.org/audio/main/_modules/torchaudio/functional/functional.html#amplitude_to_DB)  的  amp_to_db 函数。

主要的原因为什么我们不用kaldi.fbank 是因为以前这个函数不支持batch 输入，导致在线提特征很慢。

**Comment by yuyun2000** [comment]
感谢回复，再次经过@csukuangfj 倾情指路，我似乎知道问题所在了

**Comment by csukuangfj** [comment]
> 主要的原因为什么我们不用kaldi.fbank 是因为以前这个函数不支持batch 输入，导致在线提特征很慢。

@RicherMans 

Could you try https://github.com/csukuangfj/kaldifeat ?

It supports batch processing and is compatible with Kaldi.

It makes the deployment much easier.

**Comment by RicherMans** [comment]
@csukuangfj 
I will check out kaldifeat. My comment before was related to kaldi feature extraction from ~ 2020, where no batch processing was supported, which is not the case anymore.
Anyways, I'll check it out for future projects!

Regards,
Heinrich

**Comment by yuyun2000** [comment]
这样计算出来的fbank特征就是一致的了：
下面更新了新的代码

kaldi_native_fbank库是c++代码通过pybind编译的，所以在端侧部署十分方便

**Comment by lvzhiqiang** [comment]
> 这样计算出来的fbank特征就是一致的了：
> 
> ```python
> #!/usr/bin/env python3
> #
> # Copyright (c)  2023  Xiaomi Corporation (authors: Fangjun Kuang)
> 
> import pickle
> 
> import kaldi_native_fbank as knf
> import torch
> import torchaudio
> import torchaudio.transforms as aut
> import numpy as np
> def main():
>     opts = knf.FbankOptions()
>     opts.mel_opts.is_librosa= False
>     opts.mel_opts.num_bins = 64
>     opts.mel_opts.htk_mode = 1
>     opts.mel_opts.low_freq = 0
>     opts.mel_opts.norm = ""
>     opts.frame_opts.dither = 0
>     opts.frame_opts.remove_dc_offset = 0
>     opts.frame_opts.window_type = "hann"
>     opts.frame_opts.preemph_coeff = 0
>     opts.frame_opts.snip_edges = False
>     opts.frame_opts.frame_length_ms = 32
>     opts.frame_opts.frame_shift_ms = 10
>     print(opts)
>     online_whisper_fbank = knf.OnlineFbank(opts)
> 
>     wavfile = '../resources/t2.wav'
>     audio, sr = torchaudio.load(wavfile)
>     online_whisper_fbank.accept_waveform(sampling_rate=16000, waveform=audio.numpy().flatten())
>     online_whisper_fbank.input_finished()
> 
> 
>     features = []
>     for i in range(online_whisper_fbank.num_frames_ready):
>         f = online_whisper_fbank.get_frame(i)
>         f = torch.from_numpy(f)
>         features.append(f)
> 
>     features = torch.stack(features)
>     mel = features.unsqueeze(0).permute(0,2,1)
>     print(mel.shape)
> 
>     trans1 = aut.MelSpectrogram(f_min=0,
>                                 sample_rate=16000,
>                                 win_length=512,
>                                 center=True,
>                                 n_fft=512,
>                                 f_max=8000,
>                                 hop_length=160,
>                                 n_mels=64,
>                                 # mel_scale="slaney",
>                                 # norm="slaney",
>                                 )
>     trans2 = aut.AmplitudeToDB()
>     mel2 = trans1(audio)
>     mel2 = trans2(mel2)
>     print(mel2.shape)
> 
>     def cosine_similarity(vec1, vec2):
>         vec1 = vec1.flatten()#[:1000]
>         vec2 = vec2.flatten()#[:1000]
>         # 计算两个向量的点积
>         dot_product = np.dot(vec1, vec2)
>         # 计算两个向量的 L2 范数（即欧几里得范数）
>         norm_vec1 = np.linalg.norm(vec1)
>         norm_vec2 = np.linalg.norm(vec2)
>         # 计算余弦相似度
>         similarity = dot_product / (norm_vec1 * norm_vec2)
>         return similarity
> 
>     print(cosine_similarity(mel[:,:,:1000].numpy(), mel2[:,:,:1000].numpy()))
> 
> 
> if __name__ == "__main__":
>     main()
> ```
> 
> kaldi_native_fbank库是c++代码通过pybind编译的，所以在端侧部署十分方便

[[这个代码是不是有问题？测试了一条音频，两个特征的余弦相似度只有0.22，特征数值也对应不上，不知道为什么？希望大佬帮忙看下。音频如附件所示(a.wav)
[a.zip](https://github.com/RicherMans/CED/files/14571606/a.zip)
运行结果如下：
`
frame_opts: 
samp_freq: 16000
frame_shift_ms: 10
frame_length_ms: 32
dither: 0
preemph_coeff: 0
remove_dc_offset: 0
window_type: hann
round_to_power_of_two: 1
blackman_coeff: 0.42
snip_edges: 0


mel_opts: 
num_bins: 64
low_freq: 0
high_freq: 0
vtln_low: 100
vtln_high: -500
debug_mel: 0
htk_mode: 1
is_librosa: 0
norm: 

use_energy: 0
energy_floor: 0
raw_energy: 1
htk_compat: 0
use_log_fbank: 1
use_power: 1

torch.Size([1, 64, 1000])
torch.Size([1, 64, 1001])
0.22035247

`
@yuyun2000 @csukuangfj 
kaldi_native_fbank版本1.18.7, torchaudio版本2.2.0+cu118

**Comment by csukuangfj** [comment]
> > 这样计算出来的fbank特征就是一致的了：
> > ```python
> > #!/usr/bin/env python3
> > #
> > # Copyright (c)  2023  Xiaomi Corporation (authors: Fangjun Kuang)
> > 
> > import pickle
> > 
> > import kaldi_native_fbank as knf
> > import torch
> > import torchaudio
> > import torchaudio.transforms as aut
> > import numpy as np
> > def main():
> >     opts = knf.FbankOptions()
> >     opts.mel_opts.is_librosa= False
> >     opts.mel_opts.num_bins = 64
> >     opts.mel_opts.htk_mode = 1
> >     opts.mel_opts.low_freq = 0
> >     opts.mel_opts.norm = ""
> >     opts.frame_opts.dither = 0
> >     opts.frame_opts.remove_dc_offset = 0
> >     opts.frame_opts.window_type = "hann"
> >     opts.frame_opts.preemph_coeff = 0
> >     opts.frame_opts.snip_edges = False
> >     opts.frame_opts.frame_length_ms = 32
> >     opts.frame_opts.frame_shift_ms = 10
> >     print(opts)
> >     online_whisper_fbank = knf.OnlineFbank(opts)
> > 
> >     wavfile = '../resources/t2.wav'
> >     audio, sr = torchaudio.load(wavfile)
> >     online_whisper_fbank.accept_waveform(sampling_rate=16000, waveform=audio.numpy().flatten())
> >     online_whisper_fbank.input_finished()
> > 
> > 
> >     features = []
> >     for i in range(online_whisper_fbank.num_frames_ready):
> >         f = online_whisper_fbank.get_frame(i)
> >         f = torch.from_numpy(f)
> >         features.append(f)
> > 
> >     features = torch.stack(features)
> >     mel = features.unsqueeze(0).permute(0,2,1)
> >     print(mel.shape)
> > 
> >     trans1 = aut.MelSpectrogram(f_min=0,
> >                                 sample_rate=16000,
> >                                 win_length=512,
> >                                 center=True,
> >                                 n_fft=512,
> >                                 f_max=8000,
> >                                 hop_length=160,
> >                                 n_mels=64,
> >                                 # mel_scale="slaney",
> >                                 # norm="slaney",
> >                                 )
> >     trans2 = aut.AmplitudeToDB()
> >     mel2 = trans1(audio)
> >     mel2 = trans2(mel2)
> >     print(mel2.shape)
> > 
> >     def cosine_similarity(vec1, vec2):
> >         vec1 = vec1.flatten()#[:1000]
> >         vec2 = vec2.flatten()#[:1000]
> >         # 计算两个向量的点积
> >         dot_product = np.dot(vec1, vec2)
> >         # 计算两个向量的 L2 范数（即欧几里得范数）
> >         norm_vec1 = np.linalg.norm(vec1)
> >         norm_vec2 = np.linalg.norm(vec2)
> >         # 计算余弦相似度
> >         similarity = dot_product / (norm_vec1 * norm_vec2)
> >         return similarity
> > 
> >     print(cosine_similarity(mel[:,:,:1000].numpy(), mel2[:,:,:1000].numpy()))
> > 
> > 
> > if __name__ == "__main__":
> >     main()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > kaldi_native_fbank库是c++代码通过pybind编译的，所以在端侧部署十分方便
> 
> [[这个代码是不是有问题？测试了一条音频，两个特征的余弦相似度只有0.22，特征数值也对应不上，不知道为什么？希望大佬帮忙看下。音频如附件所示(a.wav) [a.zip](https://github.com/RicherMans/CED/files/14571606/a.zip) 运行结果如下： ` frame_opts: samp_freq: 16000 frame_shift_ms: 10 frame_length_ms: 32 dither: 0 preemph_coeff: 0 remove_dc_offset: 0 window_type: hann round_to_power_of_two: 1 blackman_coeff: 0.42 snip_edges: 0
> 
> mel_opts: num_bins: 64 low_freq: 0 high_freq: 0 vtln_low: 100 vtln_high: -500 debug_mel: 0 htk_mode: 1 is_librosa: 0 norm:
> 
> use_energy: 0 energy_floor: 0 raw_energy: 1 htk_compat: 0 use_log_fbank: 1 use_power: 1
> 
> torch.Size([1, 64, 1000]) torch.Size([1, 64, 1001]) 0.22035247
> 
> ` @yuyun2000 @csukuangfj kaldi_native_fbank版本1.18.7, torchaudio版本2.2.0+cu118

你能提供一个 colab 的 notebook 吗？方便我们复现。

**Comment by lvzhiqiang** [comment]
> > > 这样计算出来的fbank特征就是一致的了：
> > > ```python
> > > #!/usr/bin/env python3
> > > #
> > > # Copyright (c)  2023  Xiaomi Corporation (authors: Fangjun Kuang)
> > > 
> > > import pickle
> > > 
> > > import kaldi_native_fbank as knf
> > > import torch
> > > import torchaudio
> > > import torchaudio.transforms as aut
> > > import numpy as np
> > > def main():
> > >     opts = knf.FbankOptions()
> > >     opts.mel_opts.is_librosa= False
> > >     opts.mel_opts.num_bins = 64
> > >     opts.mel_opts.htk_mode = 1
> > >     opts.mel_opts.low_freq = 0
> > >     opts.mel_opts.norm = ""
> > >     opts.frame_opts.dither = 0
> > >     opts.frame_opts.remove_dc_offset = 0
> > >     opts.frame_opts.window_type = "hann"
> > >     opts.frame_opts.preemph_coeff = 0
> > >     opts.frame_opts.snip_edges = False
> > >     opts.frame_opts.frame_length_ms = 32
> > >     opts.frame_opts.frame_shift_ms = 10
> > >     print(opts)
> > >     online_whisper_fbank = knf.OnlineFbank(opts)
> > > 
> > >     wavfile = '../resources/t2.wav'
> > >     audio, sr = torchaudio.load(wavfile)
> > >     online_whisper_fbank.accept_waveform(sampling_rate=16000, waveform=audio.numpy().flatten())
> > >     online_whisper_fbank.input_finished()
> > > 
> > > 
> > >     features = []
> > >     for i in range(online_whisper_fbank.num_frames_ready):
> > >         f = online_whisper_fbank.get_frame(i)
> > >         f = torch.from_numpy(f)
> > >         features.append(f)
> > > 
> > >     features = torch.stack(features)
> > >     mel = features.unsqueeze(0).permute(0,2,1)
> > >     print(mel.shape)
> > > 
> > >     trans1 = aut.MelSpectrogram(f_min=0,
> > >                                 sample_rate=16000,
> > >                                 win_length=512,
> > >                                 center=True,
> > >                                 n_fft=512,
> > >                                 f_max=8000,
> > >                                 hop_length=160,
> > >                                 n_mels=64,
> > >                                 # mel_scale="slaney",
> > >                                 # norm="slaney",
> > >                                 )
> > >     trans2 = aut.AmplitudeToDB()
> > >     mel2 = trans1(audio)
> > >     mel2 = trans2(mel2)
> > >     print(mel2.shape)
> > > 
> > >     def cosine_similarity(vec1, vec2):
> > >         vec1 = vec1.flatten()#[:1000]
> > >         vec2 = vec2.flatten()#[:1000]
> > >         # 计算两个向量的点积
> > >         dot_product = np.dot(vec1, vec2)
> > >         # 计算两个向量的 L2 范数（即欧几里得范数）
> > >         norm_vec1 = np.linalg.norm(vec1)
> > >         norm_vec2 = np.linalg.norm(vec2)
> > >         # 计算余弦相似度
> > >         similarity = dot_product / (norm_vec1 * norm_vec2)
> > >         return similarity
> > > 
> > >     print(cosine_similarity(mel[:,:,:1000].numpy(), mel2[:,:,:1000].numpy()))
> > > 
> > > 
> > > if __name__ == "__main__":
> > >     main()
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > kaldi_native_fbank库是c++代码通过pybind编译的，所以在端侧部署十分方便
> > 
> > 
> > [[这个代码是不是有问题？测试了一条音频，两个特征的余弦相似度只有0.22，特征数值也对应不上，不知道为什么？希望大佬帮忙看下。音频如附件所示(a.wav) [a.zip](https://github.com/RicherMans/CED/files/14571606/a.zip) 运行结果如下： ` frame_opts: samp_freq: 16000 frame_shift_ms: 10 frame_length_ms: 32 dither: 0 preemph_coeff: 0 remove_dc_offset: 0 window_type: hann round_to_power_of_two: 1 blackman_coeff: 0.42 snip_edges: 0
> > mel_opts: num_bins: 64 low_freq: 0 high_freq: 0 vtln_low: 100 vtln_high: -500 debug_mel: 0 htk_mode: 1 is_librosa: 0 norm:
> > use_energy: 0 energy_floor: 0 raw_energy: 1 htk_compat: 0 use_log_fbank: 1 use_power: 1
> > torch.Size([1, 64, 1000]) torch.Size([1, 64, 1001]) 0.22035247
> > ` @yuyun2000 @csukuangfj kaldi_native_fbank版本1.18.7, torchaudio版本2.2.0+cu118
> 
> 你能提供一个 colab 的 notebook 吗？方便我们复现。

军歌看下这个环境可以吗？https://colab.research.google.com/drive/1h1EBaZM_MknnoLM2CSzBdJOTe5sFkdTM?usp=sharing @csukuangfj

**Comment by csukuangfj** [comment]
用这个

https://colab.research.google.com/drive/1BhFKLHk_JpqTnsXAdfGnvVQMktGxjxhX?usp=sharing

**Comment by lvzhiqiang** [comment]
> 用这个
> 
> https://colab.research.google.com/drive/1BhFKLHk_JpqTnsXAdfGnvVQMktGxjxhX?usp=sharing

使用这个环境计算得到的相似度是0.99+，但是如果将kaldi-native-fbank参数换为：
opts.mel_opts.is_librosa= False
opts.mel_opts.htk_mode = 1
opts.mel_opts.norm = ""
torchaudio melscale采用默认htk格式，相似度还是只有0.22。所以意味着kaidl-native-fbank只支持melspectrogram采用'slaney'吗 @csukuangfj

**Comment by csukuangfj** [comment]
> 所以意味着kaidl-native-fbank只支持melspectrogram采用'slaney'吗

不是的。

---

你要比较两个是否一致，就要用一样的参数。

你参数不一样，会得到不同的结果，但你不能得到 kaldi-native-fbank 只支持某一种实现。

**Comment by lvzhiqiang** [comment]
> > 所以意味着kaidl-native-fbank只支持melspectrogram采用'slaney'吗
> 
> 不是的。
> 
> 你要比较两个是否一致，就要用一样的参数。
> 
> 你参数不一样，会得到不同的结果，但你不能得到 kaldi-native-fbank 只支持某一种实现。

明白，所以我的问题是采用yuyun2000的配置能否得到ced目前使用的melspectrogram配置同样的特征，我目前采用该配置结果不一致，相似度较低，想问下军哥复现了吗

**Comment by yuyun2000** [comment]
使用以下代码可以实现计算的fbank特征与仓库中计算方法的结果相似度达0.99的结果：
```
#!/usr/bin/env python3
#
# Copyright (c)  2023  Xiaomi Corporation (authors: Fangjun Kuang)

import pickle

import kaldi_native_fbank as knf
import torch
import torchaudio
import torchaudio.transforms as aut
import numpy as np
def main():
    opts = knf.FbankOptions()
    opts.mel_opts.is_librosa= False
    opts.mel_opts.num_bins = 64
    opts.mel_opts.htk_mode = 0
    opts.mel_opts.low_freq = 0
    opts.mel_opts.norm = ""
    opts.frame_opts.dither = 0
    opts.frame_opts.remove_dc_offset = 0
    opts.frame_opts.window_type = "hann"
    opts.frame_opts.preemph_coeff = 0
    opts.frame_opts.snip_edges = False
    opts.frame_opts.frame_length_ms = 32
    opts.frame_opts.frame_shift_ms = 10
    print(opts)
    online_whisper_fbank = knf.OnlineFbank(opts)

    wavfile = '../resources/t2.wav'
    audio, sr = torchaudio.load(wavfile)
    online_whisper_fbank.accept_waveform(sampling_rate=16000, waveform=audio.numpy().flatten())
    online_whisper_fbank.input_finished()


    features = []
    for i in range(online_whisper_fbank.num_frames_ready):
        f = online_whisper_fbank.get_frame(i)
        f = torch.from_numpy(f)
        features.append(f)

    features = torch.stack(features)
    mel = features.unsqueeze(0).permute(0,2,1)
    print(mel.shape)

    trans1 = aut.MelSpectrogram(f_min=0,
                                sample_rate=16000,
                                win_length=512,
                                center=True,
                                n_fft=512,
                                f_max=8000,
                                hop_length=160,
                                n_mels=64,
                                # mel_scale="slaney",
                                # norm="slaney",
                                )
    trans2 = aut.AmplitudeToDB()
    mel2 = trans1(audio)
    mel2 = trans2(mel2)
    print(mel2.shape)

    def cosine_similarity(vec1, vec2):
        vec1 = vec1.flatten()#[:1000]
        vec2 = vec2.flatten()#[:1000]
        # 计算两个向量的点积
        dot_product = np.dot(vec1, vec2)
        # 计算两个向量的 L2 范数（即欧几里得范数）
        norm_vec1 = np.linalg.norm(vec1)
        norm_vec2 = np.linalg.norm(vec2)
        # 计算余弦相似度
        similarity = dot_product / (norm_vec1 * norm_vec2)
        return similarity

    print(cosine_similarity(mel[:,:,:1000].numpy(), mel2[:,:,:1000].numpy()))


if __name__ == "__main__":
    main()
```
再说一句，torchaudio的结果主要是没有进行预加重，所以不论你原本使用什么库进行计算，把预加重系统设置为0，最后的结果都不会偏离太多的，比如：
```
import torchaudio.compliance.kaldi as kaldi
mat = kaldi.fbank(wav,
                  num_mel_bins=64,
                  frame_length=32,
                  frame_shift=10,
                  dither=0.0,
                  energy_floor=0.0,
                  sample_frequency=16000,
                  window_type='hamming',
                preemphasis_coefficient=0,
                snip_edges=False
                  )
```

**Comment by yuyun2000** [comment]
Why do you always have a keen eye for every issue's comment?

Fangjun Kuang ***@***.***> 于2024年3月13日周三 16:03写道：

**Comment by Dxymiemiemie** [comment]
I've been working with the fbank feature extraction module from Kaldi in Python, and now I'm looking to port the preprocessing part to C++. Specifically, I want to convert the preprocessing steps from the Python version to C++.

Could anyone provide guidance on how to accomplish this? I'm particularly interested in translating the steps for computing filterbank energies, applying pre-emphasis, and any other necessary preprocessing steps. If there are existing libraries or examples that demonstrate this conversion, I'd greatly appreciate pointers to them.

Thank you for your assistance!

**Comment by csukuangfj** [comment]
please see 

[kaldi-native-fbank](https://github.com/csukuangfj/kaldi-native-fbank)

**Comment by Dxymiemiemie** [comment]
> please see 
> 
> kaldi-native-fbank

OK, I mean is there any dynamic library of guidance to implememt this function in C directly?It would be much easier.

**Comment by yuyun2000** [comment]
> > please see
> > kaldi-native-fbank
> 
> OK, I mean is there any dynamic library of guidance to implememt this function in C directly?It would be much easier.

如果你去看了，你就不会问了

**Comment by csukuangfj** [comment]
能这么问，应该是不想去看的。

都喂到嘴边了
